# frozen_string_literal: true

Minibootcamp.create(unique_id: 'bootcamp', content_type: 0)
Minibootcamp.create(unique_id: 'HTML', parent_id: 'bootcamp', content_type: 1)
Minibootcamp.create(unique_id: 'html-mod-1', parent_id: 'HTML', content_type: 2, markdown: 'hello')
Minibootcamp.create(unique_id: 'html-mod-2', parent_id: 'HTML', content_type: 2, markdown: 'hello')
Minibootcamp.create(unique_id: 'html-mod-3', parent_id: 'HTML', content_type: 2, markdown: 'world')
Minibootcamp.create(unique_id: 'html-mod-4', parent_id: 'HTML', content_type: 2, markdown: 'lakshit')
Minibootcamp.create(unique_id: 'html-mod-5', parent_id: 'HTML', content_type: 2, markdown: 'kaydee')
Minibootcamp.create(unique_id: 'CSS', parent_id: 'bootcamp', content_type: 1)
Minibootcamp.create(unique_id: 'css-mod-1', parent_id: 'CSS', content_type: 2, markdown: 'getthereveryfastindeed')
Minibootcamp.create(unique_id: 'css-mod-2', parent_id: 'CSS', content_type: 2, markdown: 'HELLO CSS')
Minibootcamp.create(unique_id: 'css-mod-3', parent_id: 'CSS', content_type: 2, markdown: 'world')
Minibootcamp.create(unique_id: 'css-mod-4', parent_id: 'CSS', content_type: 2, markdown: 'MODULE 4')
Minibootcamp.create(unique_id: 'css-mod-5', parent_id: 'CSS', content_type: 2, markdown: 'MODULE 5')
Minibootcamp.create(unique_id: 'Javascript', parent_id: 'bootcamp', content_type: 1)
Minibootcamp.create(unique_id: 'js-mod-1', parent_id: 'Javascript', content_type: 2, markdown: 'hello')
Minibootcamp.create(unique_id: 'js-mod-2', parent_id: 'Javascript', content_type: 2, markdown: 'WORLD')
Minibootcamp.create(unique_id: 'js-mod-2', parent_id: 'Javascript', content_type: 2, markdown: 'HELLO JS')
Minibootcamp.create(unique_id: 'js-mod-3', parent_id: 'Javascript', content_type: 2, markdown: 'MODULE 3')
Minibootcamp.create(unique_id: 'js-mod-4', parent_id: 'Javascript', content_type: 2, markdown: 'MODULE 4')
