name: Ruby

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MYSQL_NAME: devsnest_test
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      DISCORD_TOKEN: 1234567890qwertyuiop
      CC_TEST_REPORTER_ID: 8f0038687a9ad7675365b6a1ecde37608d55e4fa148d2da81a0653dc1dc6937d
      CC_TEST_REPORTER_URL: https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
      REDIS_DB: devsnest_lb_test
      REDIS_DB_LB: devsnest_lb_test_lb
      REDIS_URL: redis://127.0.0.1:6379
      REDIS_HOST_LB: redis://127.0.0.1:6379
      SECRET_KEY_BASE: qC3vQNz76DAjsmOPEuLf6nGPi7WMf+zV # this string is random, don't raise issue for this
      LISTMONK_HOST: ${{ secrets.LISTMONK_HOST }}
      LISTMONK_USERNAME: ${{ secrets.LISTMONK_USERNAME }}
      LISTMONK_PASSWORD: ${{ secrets.LISTMONK_PASSWORD }}

    services:
      redis:
        image: redis
        ports:
        - 6379:6379

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: setup-ruby@v1.138.0 
        with:
          ruby-version: 3.0.6
          bundler-cache: true


      - name: Start mysqld
        run: sudo systemctl start mysql.service
      - name: Create database
        run: mysql -u root --password=root -e 'create database devsnest_test';


      - name: Download test coverage reporter
        working-directory: ./devsnest
        run: curl -L $CC_TEST_REPORTER_URL > cc-test-reporter

      - name: Give test coverage reporter executable permissions
        working-directory: ./devsnest
        run: chmod +x cc-test-reporter

      - name: Run Tests
        env:
          RAILS_ENV: test
        working-directory: ./devsnest
        run: |
            bundle install --jobs 4 --retry 3
            bundle exec rake db:create
            bundle exec rake db:migrate
            bundle exec rspec --exclude-pattern "spec/backend_challenge/*_spec.rb"
            
      - name: Upload results to Code Climate
        working-directory: ./devsnest
        run: |
          ./cc-test-reporter format-coverage -t simplecov -o coverage/codeclimate.json
          ./cc-test-reporter upload-coverage
